# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'num_pad.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(190, 242)
        Form.setStyleSheet("#Form{\n"
"    background-color: rgb(232, 242, 247);\n"
"}")
        self.bir = QtWidgets.QPushButton(Form)
        self.bir.setGeometry(QtCore.QRect(10, 13, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bir.setFont(font)
        self.bir.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.bir.setObjectName("bir")
        self.iki = QtWidgets.QPushButton(Form)
        self.iki.setGeometry(QtCore.QRect(70, 13, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.iki.setFont(font)
        self.iki.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.iki.setObjectName("iki")
        self.uc = QtWidgets.QPushButton(Form)
        self.uc.setGeometry(QtCore.QRect(130, 13, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.uc.setFont(font)
        self.uc.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.uc.setObjectName("uc")
        self.dord = QtWidgets.QPushButton(Form)
        self.dord.setGeometry(QtCore.QRect(10, 70, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dord.setFont(font)
        self.dord.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.dord.setObjectName("dord")
        self.bes = QtWidgets.QPushButton(Form)
        self.bes.setGeometry(QtCore.QRect(70, 70, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bes.setFont(font)
        self.bes.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.bes.setObjectName("bes")
        self.alti = QtWidgets.QPushButton(Form)
        self.alti.setGeometry(QtCore.QRect(130, 70, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.alti.setFont(font)
        self.alti.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.alti.setObjectName("alti")
        self.yeddi = QtWidgets.QPushButton(Form)
        self.yeddi.setGeometry(QtCore.QRect(10, 130, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yeddi.setFont(font)
        self.yeddi.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.yeddi.setObjectName("yeddi")
        self.sekkiz = QtWidgets.QPushButton(Form)
        self.sekkiz.setGeometry(QtCore.QRect(70, 130, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sekkiz.setFont(font)
        self.sekkiz.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.sekkiz.setObjectName("sekkiz")
        self.doqquz = QtWidgets.QPushButton(Form)
        self.doqquz.setGeometry(QtCore.QRect(130, 130, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.doqquz.setFont(font)
        self.doqquz.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.doqquz.setObjectName("doqquz")
        self.sifir = QtWidgets.QPushButton(Form)
        self.sifir.setGeometry(QtCore.QRect(70, 188, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sifir.setFont(font)
        self.sifir.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.sifir.setObjectName("sifir")
        self.ok = QtWidgets.QPushButton(Form)
        self.ok.setGeometry(QtCore.QRect(130, 188, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ok.setFont(font)
        self.ok.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.ok.setObjectName("ok")
        self.sil = QtWidgets.QPushButton(Form)
        self.sil.setGeometry(QtCore.QRect(10, 188, 50, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sil.setFont(font)
        self.sil.setStyleSheet("QPushButton{    \n"
"    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: rgb(225, 235, 239);\n"
"    border:1px solid;\n"
"    \n"
"    border-color: rgb(11, 134, 200);\n"
"}\n"
"QPushButton:pressed{    \n"
"    \n"
"    background-color: rgb(74, 128, 193);\n"
"    border:1px solid;\n"
"    border-color: rgb(161, 161, 161);\n"
"}")
        self.sil.setObjectName("sil")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Num Pad"))
        self.bir.setText(_translate("Form", "1"))
        self.iki.setText(_translate("Form", "2"))
        self.uc.setText(_translate("Form", "3"))
        self.dord.setText(_translate("Form", "4"))
        self.bes.setText(_translate("Form", "5"))
        self.alti.setText(_translate("Form", "6"))
        self.yeddi.setText(_translate("Form", "7"))
        self.sekkiz.setText(_translate("Form", "8"))
        self.doqquz.setText(_translate("Form", "9"))
        self.sifir.setText(_translate("Form", "0"))
        self.ok.setText(_translate("Form", "OK"))
        self.sil.setText(_translate("Form", "⌫"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
