# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pass_sc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(436, 291)
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.setFont(font)
        Form.setAccessibleName("")
        Form.setStyleSheet("#Form{\n"
"    background-color:#E8F2F7;\n"
"}")
        Form.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 13, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 13, 41, 44))
        self.label_2.setStyleSheet("image: url(:/newPrefix/logo.JPG);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/logo.JPG"))
        self.label_2.setScaledContents(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 50, 101, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(70, 80, 351, 25))
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: #F0F6F9;\n"
"    border-color:#DAE4E9;\n"
"    color:black;\n"
"}\n"
"")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.NoEcho)
        self.lineEdit.setPlaceholderText("Cross")
        self.lineEdit.setObjectName("lineEdit")
        self.password_lineedit = QtWidgets.QLineEdit(Form)
        self.password_lineedit.setGeometry(QtCore.QRect(70, 140, 294, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_lineedit.setFont(font)
        self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineedit.setPlaceholderText("")
        self.password_lineedit.setObjectName("password_lineedit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 110, 191, 31))
        self.label_4.setObjectName("label_4")
        self.forgot_button = QtWidgets.QPushButton(Form)
        self.forgot_button.setGeometry(QtCore.QRect(70, 200, 108, 19))
        self.forgot_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgot_button.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    color: rgb(53, 125, 196);\n"
"}\n"
"QPushButton:hover{\n"
"    color:red;\n"
"}")
        self.forgot_button.setObjectName("forgot_button")
        self.digit_pass = QtWidgets.QPushButton(Form)
        self.digit_pass.setGeometry(QtCore.QRect(375, 134, 40, 34))
        self.digit_pass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.digit_pass.setStyleSheet("image: url(:/newPrefix/mini.JPG);\n"
"border:1px solid;\n"
"border-color: rgb(134, 134, 134);")
        self.digit_pass.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/mini.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.digit_pass.setIcon(icon)
        self.digit_pass.setIconSize(QtCore.QSize(400, 400))
        self.digit_pass.setObjectName("digit_pass")
        self.ok = QtWidgets.QPushButton(Form)
        self.ok.setGeometry(QtCore.QRect(250, 240, 79, 32))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ok.setFont(font)
        self.ok.setStyleSheet("QPushButton{\n"
"    border:1px solid;\n"
"    background-color: rgb(128, 214, 253);\n"
"    border-color: rgb(116, 116, 116);\n"
"}\n"
"QPushButton:hover{\n"
"    border:1px solid;\n"
"    background-color: rgb(128, 214, 253);\n"
"    \n"
"    border-color: rgb(48, 48, 48);\n"
"}")
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(340, 240, 80, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("QPushButton{\n"
"    border:1px solid;\n"
"    background-color: rgb(232, 241, 246);\n"
"    border-color: rgb(112, 112, 112);\n"
"}\n"
"QPushButton:hover{\n"
"    border:1px solid;\n"
"    \n"
"    background-color: rgb(128, 214, 253);\n"
"    border-color: rgb(112, 112, 112);\n"
"}")
        self.cancel.setObjectName("cancel")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.password_lineedit.raise_()
        self.label_4.raise_()
        self.lineEdit.raise_()
        self.forgot_button.raise_()
        self.digit_pass.raise_()
        self.ok.raise_()
        self.cancel.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "My Lockbox  Password"))
        self.label.setText(_translate("Form", "My Lockbox™"))
        self.label_3.setText(_translate("Form", "Password hint:"))
        self.label_4.setText(_translate("Form", "Please enter the password here"))
        self.forgot_button.setText(_translate("Form", "Forgot password?"))
        self.ok.setText(_translate("Form", "OK"))
        self.cancel.setText(_translate("Form", "Cancel"))
import img


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
